#!/bin/bash

cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"

N_CELLS="${N_CELLS:-10}"
sed "s/NCELLS/${N_CELLS}/g" \
    system/blockMeshDict.template > system/blockMeshDict.active

runApplication blockMesh -dict system/blockMeshDict.active
rm -f system/blockMeshDict.active
runApplication cardiacFoam

