#!/bin/bash
# Manufactured interface diagnostics of the bath-bidomain result
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions

runApplication bathBidomainInterfaceMetrics -latestTime || exit 1
