#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication ionicHeterogeneityProbe
probe_status=$?

if [ "$probe_status" -ne 0 ]; then
    echo "ionicHeterogeneityProbe returned $probe_status; plotting generated data anyway."
fi

if command -v python3 >/dev/null 2>&1; then
    MPLCONFIGDIR="${TMPDIR:-/tmp}/matplotlib-cardiacfoam" \
        python3 ../../../applications/utilities/ionicHeterogeneityProbe/plotIonicHeterogeneityProbe.py \
        postProcessing/ionicHeterogeneityProbe
else
    echo "python3 was not found. Plot manually with:"
    echo "  python3 ../../../applications/utilities/ionicHeterogeneityProbe/plotIonicHeterogeneityProbe.py postProcessing/ionicHeterogeneityProbe"
fi

exit "$probe_status"
