#!/usr/bin/env python3

import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
SRC_DIR = SCRIPT_DIR
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from pipeline import (
    detect_start_stage,
    run_pipeline,
    split_model_spec,
)
from sort_folder import sort_folder


UTILITY_NAME = "cellML2foam"


def foam_banner(args, start, stages):
    print(f"--> {UTILITY_NAME}")
    print(f"    Input        : {args.input}")
    print(f"    Start stage  : {start}")
    print(f"    End stage    : {args.to}")
    print(f"    Model name   : {args.model}")
    print(f"    Output dir   : {args.outdir}")
    print(f"    Pipeline     : {' -> '.join(stages)}")
    print("")


def print_manual_steps_notice(model_kind: str):
    if model_kind == "activeTension":
        print(
            """
============================================================
MANUAL STEPS REQUIRED
============================================================

The generated OpenFOAM active tension model requires manual edits
before it is ready for use.

1) Ca equation consistency
-----------------------------------------------
Check for the Ca equation and make sure it is properly defined
in both Model.C and Model_Year.H.

2) Model requirements in Model.H
-----------------------------------------------
Update the Requirements flags in Model.H to match your model inputs
(Vm, Act, Ca). For example:

    Requirements r;
    r.needVm  = true;
    r.needAct = true;
    r.needCai = true;

3) Remove unused time terms
-----------------------------------------------
Remove unused time from model.H and modelNames.H and replace with VOI

    Examples: AV_<variable>, t, pace, t_end

    Hint: During compilation, ones should appear if not used.

4) Hash table for voltage, Act, or Ca dependence
-----------------------------------------------
If the model has dependence on Vm, Act, or Ca parameters,
implement the hash table lookup in <ModelName_Year>.H.
    Example:

        {"INa",
              Foam::wordList
              ({
                  "m_inf","h_inf","j_inf",
                  "tau_m","tau_h","tau_j"
               })}

Check the existing examples in the cardiacFoam library in src/ionicModels.

============================================================
"""
        )
        return

    print(
        """
============================================================
MANUAL STEPS REQUIRED
============================================================

The generated OpenFOAM ionic model requires three manual edits
before it is ready for use.

1) Define ALGEBRAIC[Iion_cm]
--------------------------------
You must define the transmembrane ionic current as the sum of
all ionic currents in the model. 

    Hint: Look for the definition of RATES[V] 

Example (illustrative):

    ALGEBRAIC[Iion_cm] =
        ALGEBRAIC[INa]
      + ALGEBRAIC[ICaL]
      + ALGEBRAIC[IKr]
      + ALGEBRAIC[IKs]
      + ALGEBRAIC[IK1]
      + ...
      - ALGEBRAIC [AV_Istim]

This definition is model-specific and must be verified
against the original publication.


2) Remove redundant voltage and stimulus terms
-----------------------------------------------
Please inspect the functions and:

- Remove the existing RATES[V], as referred, generated by Myokit
  (Vm is handled at the end of the function for OpenFOAM)

- Remove unused stimulus-related from model.H and modelNames.H

    Examples: AV_<variable>, t, pace, t_amplitude, t_end,

    Hint: During compilation, ones should appear if not used.


3) flags for tissue definition
-----------------------------------------------
- If there is data dependant on tissue type, map the used variable to tissueFlag:

    tissueFlag == 1 : endo
    tissueFlag == 2 : mid
    tissueFlag == 3 : epi

4) Hash table for voltage dependance 
-----------------------------------------------
If the model has voltage dependance on parameters 
(e.g., gatingvariables), you just need to implement the hash table lookup 
for Vm existing in <ModelName_Year>.H. 
    Example:

        {"INa",
              Foam::wordList
              ({
                  "m_inf","h_inf","j_inf",
                  "tau_m","tau_h","tau_j"
               })}
               
Check the existing examples in the cardiacFoam library in src/ionicModels.

============================================================
"""
    )


def parse_args():
    p = argparse.ArgumentParser(
        prog=UTILITY_NAME,
        description="Convert CellML models to OpenFOAM-ready ionic model code",
    )

    p.add_argument(
        "input",
        type=Path,
        help="Input file (.cellml, .mmt, .c)",
    )

    p.add_argument(
        "--from",
        dest="start",
        help="Pipeline stage to start from (auto-detected if omitted)",
    )

    p.add_argument(
        "--to",
        dest="to",
        default="openfoam",
        help="Pipeline stage to end at (default: openfoam)",
    )

    p.add_argument(
        "--model",
        help="Model name (used for output files)",
    )

    p.add_argument(
        "--outdir",
        type=Path,
        default=Path("."),
        help="Output directory (default: current directory)",
    )

    p.add_argument(
        "--verbose",
        action="store_true",
        help="Verbose output",
    )

    return p.parse_args()


def main():
    args = parse_args()

    if not args.input.exists():
        print(f"Error: input file not found: {args.input}")
        sys.exit(1)

    try:
        start = args.start or detect_start_stage(args.input)

        # Preview pipeline
        stages = run_pipeline(
            args.input,
            start=start,
            end=args.to,
            model=args.model,
            verbose=args.verbose,
        )

        if stages is not None:
            foam_banner(args, start, stages)
            # Only create ionic folder if we reached openfoam
        if args.to == "openfoam":
            if args.model is None:
                raise ValueError("--model <ModelName_Year>[:ionic|activeTension] is required")

            model_base, model_kind = split_model_spec(args.model)

            if "_" not in model_base:
                raise ValueError("--model must be ModelName_Year[:ionic|activeTension]")

            model, year = model_base.rsplit("_", 1)
            year = int(year)

            sort_result = sort_folder(
                model=model,
                year=year,
                outdir=args.outdir,
                model_kind=model_kind,
                verbose=args.verbose,
            )
            if args.verbose:
                print(f"    Created: {len(sort_result['created'])} files")
                print(f"    Moved:   {len(sort_result['moved'])} files")
            print_manual_steps_notice(model_kind)

    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
