#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Check if OpenFOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM bashrc first!"
    exit 1
else
    allowed_ver=(
        "v2512" "v2506" "v2412" "v2406" "v2312"
    )
    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]; then
        echo "Unsupported OpenFOAM version sourced!"
    fi
fi


# Clean libraries
(cd src && ./Allwclean)

# Clean applications
(cd applications && ./Allwclean)

# Clean all tutorials
(cd tutorials && ./Allclean)

# Clear the tutorialsTest directory
if [[ -d tutorialsTest ]]
then
    echo; echo "Removing tutorialsTest"
    rm -rf tutorialsTest
fi

# Clear all build logs
echo; echo "Removing all log.Allwmake build logs"; echo
find . -name log.Allwmake | xargs rm
