#!/bin/bash

cd "${0%/*}" || exit 1

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf case.foam monitorFile postProcessing
rm -rf regressionTests
rm -rf constant/polyMesh
rm -f  setup/slab.geo slab.msh
rm -f  log.*
