#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf case.foam monitorFile postProcessing
rm -f log.*
rm -f constant/electroProperties.withDefaultValues

# Explicit fallback for solved time directories: cleanCase/cleanTimeDirectories
# have been observed to silently no-op in some shell states, leaving solved
# fields behind. These are solver output, never source data.
find . -maxdepth 1 -regex '\./-?[0-9]+\(\.[0-9]+\)?' ! -name '0' -exec rm -rf {} +

# The mesh and anatomy fields are copied in from ../mesh/ by Allrun, not
# supplied source in this case directory - remove the copies. t is
# derived by setExprFields from tm, also not source. constant/electroProperties
# and system/controlDict are symlinks to whichever variant
# (monodomain/eikonal/hybrid) was last selected by Allrun.
rm -rf constant/polyMesh
rm -f 0/fiber 0/sheet 0/sheetNormal 0/tm 0/tv 0/apicobasal 0/Conductivity 0/t
rm -f constant/purkinjeGraph constant/electroProperties system/controlDict
