from typing import Final, Any
from openfoam_driver.core.contracts.dictionary import DictEntry, build_group

HETEROGENEITY_MODELS: tuple[str, ...] = (
    "BuenoOrovio", "TNNP", "TWorld", "ToRORd_dynCl",
    "AlievPanfilov", "Courtemanche", "Fabbri", "Gaur",
    "Grandi", "PerisYague", "Stewart", "Trovato",
    "BuenoOroviocompactBatched", "TNNPcompactBatched",
    "TWorldcompactBatched", "ToRORd_dynClcompactBatched",
)

ELECTRO_PROPERTY_ENTRY_GROUPS: Final[dict[str, tuple[DictEntry, ...]]] = {
    "top_level": build_group(
        defaults={},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.cellZone',
            phases=frozenset({'anatomy'}),
            description='Optional cell zone name. Restricts the myocardium domain and equations to a specific subset of the mesh cells.',
            source_refs=('src/electroModels/electroDomains/myocardiumDomain/myocardiumDomain.C', 'src/electroModels/electroDomains/myocardiumDomain/eikonalMyocardiumDomain.C'),
            notes='Read from the resolved <solver>Coeffs block, NOT the electroProperties root: myocardiumDomain.C:35-52 queries the coeffs dictionary (electroModel.C:109 builds it as subDict(type + "Coeffs")). This path was previously catalogued bare, which emitted it at the file root where nothing reads it -- the run then silently used the whole mesh, bath included, instead of the requested zone.',
            value_kind='word',
        ),
        DictEntry(
            driver_path='myocardiumSolver',
            phases=frozenset({'physics'}),
            description="Top-level myocardium solver selector. Determines the active '<solver>Coeffs' sub-dictionary in electroProperties.",
            source_refs=('src/electroModels/core/electroModel.C', 'src/electroModels/core/electrophysiologyModel/electrophysiologyModel.C', 'src/electroModels/electroDomains/myocardiumDomain/myocardiumSolver.C', 'src/electroModels/myocardiumModels/monodomainSolver/monodomainSolver.C', 'src/electroModels/myocardiumModels/bidomainSolver/bidomainSolver.C', 'src/electroModels/myocardiumModels/singleCellSolver/singleCellSolver.C', 'src/electroModels/electroDomains/myocardiumDomain/eikonalMyocardiumDomain.C'),
            notes='Dictionary values are top-level myocardiumSolver choices. monodomainSolver and bidomainSolver dispatch through the myocardiumSolver RTST inside electrophysiologyModel; singleCellSolver is registered in the parent electroModel RTST; eikonalSolver selects the electrophysiologyModel wrapper and then builds an eikonalMyocardiumDomain, not the legacy 3D eikonalSolver class.',
            value_kind='enum',
            enum_values=('monodomainSolver', 'bidomainSolver', 'singleCellSolver', 'eikonalSolver'),
            required=True,
        ),
        ),
    ),
    "common_model_coeffs": build_group(
        defaults={},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.solutionAlgorithm',
            phases=frozenset({'solver'}),
            description="Diffusion step time-discretisation for monodomain and bidomain solvers. 'explicit' uses an operator-split forward-Euler diffusion step; 'implicit' uses a pimple-controlled implicit solve. Not applicable to eikonalSolver (steady BVP) or singleCellSolver (no diffusion).",
            source_refs=('src/electroModels/electroDomains/myocardiumDomain/myocardiumDomain.C',),
            value_kind='enum',
            enum_values=('implicit', 'explicit'),
            constraints=('Only applicable when myocardiumSolver is monodomainSolver or bidomainSolver.',),
            typical_value='explicit',
            forbidden_when={"myocardiumSolver": ("eikonalSolver", "singleCellSolver")},
            required_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.activationThreshold',
            phases=frozenset({'solver'}),
            description='Vm threshold (volts) used to detect cell activation onset. A cell is marked as activated when Vm crosses this value upward. Default 0.0 V (rest potential for most models).',
            source_refs=('src/electroModels/electroDomains/myocardiumDomain/myocardiumDomain.C',),
            value_kind='scalar',
            typical_value='0.0',
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicModel',
            phases=frozenset({'physics'}),
            description='Ionic cell model selector.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C',),
            value_kind='enum',
            enum_values=('AlievPanfilov', 'BuenoOrovio', 'Courtemanche', 'Fabbri', 'Gaur', 'Grandi', 'PerisYague', 'Stewart', 'TNNP', 'ToRORd_dynCl', 'Trovato', 'TWorld', 'bathBidomainFDAManufactured', 'bidomainFDAManufactured', 'monodomainFDAManufactured', 'AlievPanfilovcompactBatched', 'BuenoOroviocompactBatched', 'CourtemanchecompactBatched', 'FabbricompactBatched', 'GaurcompactBatched', 'GrandicompactBatched', 'PerisYaguecompactBatched', 'StewartcompactBatched', 'TNNPcompactBatched', 'ToRORd_dynClcompactBatched', 'TrovatocompactBatched', 'TWorldcompactBatched'),
            required_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver", "singleCellSolver")},
            constraints=('Not applicable when myocardiumSolver=eikonalSolver.',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.tissue',
            phases=frozenset({'physics'}),
            description='Tissue selector for ionic-model specialisation.',
            source_refs=('src/ionicModels/ionicModel/ionicSelector.C',),
            value_kind='enum',
            enum_values=('epicardialCells', 'mCells', 'endocardialCells', 'myocyte'),
            required=True,
            constraints=('Not applicable when myocardiumSolver=eikonalSolver or ionicModel is a manufactured model.',),
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver", "singleCellSolver"), "ionicModel": ("AlievPanfilov", "BuenoOrovio", "Courtemanche", "Fabbri", "Gaur", "Grandi", "PerisYague", "Stewart", "TNNP", "ToRORd_dynCl", "Trovato", "TWorld", "AlievPanfilovcompactBatched", "BuenoOroviocompactBatched", "CourtemanchecompactBatched", "FabbricompactBatched", "GaurcompactBatched", "GrandicompactBatched", "PerisYaguecompactBatched", "StewartcompactBatched", "TNNPcompactBatched", "ToRORd_dynClcompactBatched", "TrovatocompactBatched", "TWorldcompactBatched")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.sex',
            phases=frozenset({'physics'}),
            description='Optional biological sex selector for ionic models that expose sex-specific variants.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/ionicModels/ionicModel/ionicSelector.C', 'src/ionicModels/TWorld/TWorld.C'),
            value_kind='enum',
            enum_values=('neutral', 'male', 'female'),
            constraints=('Only applicable for ionic models whose supportedSexTypes() includes the selected value.',),
            applicable_when={"ionicModel": ("TWorld", "TWorldBatched")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.electrophysicsAdvanceScheme',
            phases=frozenset({'solver'}),
            description='Time-advance scheme for multi-domain coupling (myocardium, Purkinje, ECG).',
            source_refs=('src/electroModels/core/advanceSchemes/electrophysicsAdvanceScheme.H', 'src/electroModels/core/advanceSchemes/staggered/staggeredElectrophysicsAdvanceScheme.C'),
            notes='staggeredElectrophysicsAdvanceScheme: ordered coupling for myocardium, optional bath potential, Purkinje, and ECG domains.',
            value_kind='enum',
            enum_values=('staggeredElectrophysicsAdvanceScheme',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.dimension',
            phases=frozenset({'physics'}),
            description='Dimensional selector used by manufactured/verification ionic models.',
            source_refs=('src/ionicModels/ionicModel/ionicSelector.C',),
            value_kind='enum',
            enum_values=('1D', '2D', '3D'),
            constraints=('Only applicable for manufactured ionic models (monodomainFDAManufactured, bidomainFDAManufactured, bathBidomainFDAManufactured).',),
            applicable_when={"ionicModel": ("monodomainFDAManufactured", "bidomainFDAManufactured", "bathBidomainFDAManufactured")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.writeAfterTime',
            phases=frozenset({'solver'}),
            description='Suppresses single-cell trace output before the given time.',
            source_refs=('src/genericWriter/ionicModelIO.C',),
            value_kind='scalar',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.writeFrequency',
            phases=frozenset({'solver'}),
            description='Output period (seconds) for single-cell trace writing. When set, a row is emitted only when a writeFrequency boundary is crossed between the previous and current time. Omit (or set to 0) to write every step.',
            source_refs=('src/genericWriter/ionicModelIO.C',),
            value_kind='scalar',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.utilities',
            phases=frozenset({'physics'}),
            description='Utility mode flag for ionic-model helper applications.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C',),
            value_kind='boolean',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.initSampleCell',
            phases=frozenset({'physics'}),
            description='Integration-point index used for sampled single-cell style output.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C',),
            value_kind='integer',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.outputVariables.ionic.export',
            phases=frozenset({'solver'}),
            description="Ionic variables exported to volumetric fields or trace output. Names are filtered against the active ionic model's state and algebraic-variable lists (model-dependent). 'Vm' and 'Iion' are aliased universally (resolve to the model's voltage state and total ionic current via ionicVariableCompatibility.C). Unknown names are silently dropped with a runtime warning at ionicModelIO.C:417. NOT consumed by eikonalSolver (no ionic model owned). 'activationTime' is NOT a valid ionic variable; it is a Purkinje conduction-system field.",
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/genericWriter/ionicModelIO.C', 'src/genericWriter/ionicVariableCompatibility.C'),
            value_kind='word_list',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.outputVariables.ionic.debug',
            phases=frozenset({'solver'}),
            description='Ionic variables printed in debug output. Same filtering and aliasing rules as outputVariables.ionic.export.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/genericWriter/ionicModelIO.C'),
            value_kind='word_list',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.outputVariables.activeTension.export',
            phases=frozenset({'solver'}),
            description='Active-tension variables exported to fields or traces.',
            source_refs=('src/activeTensionModels/activeTensionModel/activeTensionModel.H',),
            value_kind='word_list',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.outputVariables.activeTension.debug',
            phases=frozenset({'solver'}),
            description='Active-tension variables printed in debug output.',
            source_refs=('src/activeTensionModels/activeTensionModel/activeTensionModel.H',),
            value_kind='word_list',
        ),
        ),
    ),
    "ionic_heterogeneity": build_group(
        defaults={"phases": frozenset({'physics'}), "applicable_when": {"$ionicHeterogeneity_supported": True}},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.field',
            description='Name of the transmural-distance field (0=endo, 1=epi) that drives the heterogeneity blend. Read by the myocardium domain when an ionicHeterogeneity block is present.',
            source_refs=('src/electroModels/electroDomains/myocardiumDomain/myocardiumDomainInterface.C',),
            value_kind='word',
            examples=('t',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.apexBaseBands.field',
            description='Name of the apicobasal-distance field (0=apex, 1=base).',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='word',
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.apexBaseBands.beta',
            description='Beta parameter.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='scalar',
            constraints=('Value must be > 0',),
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.apexBaseBands.scalingMin',
            description='Minimum scaling.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='scalar',
            constraints=('Must be < scalingMax',),
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.apexBaseBands.scalingMax',
            description='Maximum scaling.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='scalar',
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.apexBaseBands.variables',
            description='Variables to scale.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='wordList',
            applicable_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.mode',
            description='Heterogeneity application mode.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/ionicModels/ionicModel/ionicHeterogeneity.C'),
            value_kind='enum',
            enum_values=('transmuralBands', 'namedRegions', 'cellZoneRegions'),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.regions.<region_name>.baseline',
            description='Baseline phenotype for the region (e.g. endocardialCells, mCells, epicardialCells).',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='word',
            dynamic_path=True,
            applicable_when={"$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.mode": ("namedRegions", "cellZoneRegions")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.regions.<region_name>.cellZone',
            description='Mesh cellZone name defining the bounds of the region.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='word',
            dynamic_path=True,
            applicable_when={"$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.mode": ("cellZoneRegions",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.regions.<region_name>.range',
            description='Spatial interval [min, max] for the region along the transmural field.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='scalarList',
            dynamic_path=True,
            applicable_when={"$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.mode": ("namedRegions",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.endoMInterface',
            description='Transmural position of the endocardium/M-cell boundary, normalized in (0, mEpiInterface). Defaults to 0.3 in the solver.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/ionicModels/ionicModel/ionicHeterogeneity.C'),
            value_kind='scalar',
            constraints=('Must be > 0 and < mEpiInterface.',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.mEpiInterface',
            description='Transmural position of the M-cell/epicardium boundary, normalized in (endoMInterface, 1). Defaults to 0.7 in the solver.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/ionicModels/ionicModel/ionicHeterogeneity.C'),
            value_kind='scalar',
            constraints=('Must be > endoMInterface and < 1.',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.transitionWidth',
            description='Width of the smooth transition band between tissue regions. 0 selects hard (sharp) transitions. Defaults to 0.1 in the solver.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C', 'src/ionicModels/ionicModel/ionicHeterogeneity.C'),
            value_kind='scalar',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.transitionMode',
            description='Transition style between tissue bands.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='enum',
            enum_values=('blend', 'hard'),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicHeterogeneity.smoothing',
            description='Smoothing curve applied within transition bands.',
            source_refs=('src/ionicModels/ionicModel/ionicHeterogeneity.C',),
            value_kind='enum',
            enum_values=('smoothstep',),
        ),
        ),
    ),
    "ionic_constant_overrides": build_group(
        defaults={"phases": frozenset({'physics'}), "source_refs": ("src/genericWriter/ionicModelIO.C", "src/ionicModels/ionicModel/ionicModel.C")},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicConstantOverrides.<scope>.scale.<constant_name>',
            description="Scale an ionic model constant by a multiplicative factor. Use for drug effects, channelopathies, or ischaemia: e.g. halving IKr conductance for LQT2/hERG block. <scope> is 'global' (every cell) or a tissue scope; global is applied first, then the ONE tissue scope matching each cell's tissue. scale is applied before set; using both on the same constant is an error.",
            notes="<constant_name> must be EXACTLY a name from this model's 'constants' list in ionic_model_catalog.py -- an unknown name is a solver FatalError (ionicModelIO.C:245-255). Do NOT assume a prefix: naming differs per model. AC_-prefixed for AlievPanfilov, Courtemanche, Fabbri, Gaur, Grandi, PerisYague, Stewart, ToRORd_dynCl, Trovato; unprefixed for BuenoOrovio, TNNP and the FDA manufactured models; and TWorld is mixed (273 AC_* plus a bare gnalTissueScale). The split is by provenance -- CellML-generated constants carry AC_, hand-added ones do not -- so it grows over time. The catalog is verified against the built solver by test_ionic_catalog_live_verification.py.",
            value_kind='scalar',
            dynamic_path=True,
            constraints=("<scope> must be one of: global, epicardialCells, mCells, endocardialCells, myocyte (ionicModelIO.C:182-189). A tissue scope applies only to cells carrying that tissue flag; global applies to all.",),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ionicConstantOverrides.<scope>.set.<constant_name>',
            description="Set an ionic model constant to an absolute value, overriding the model default entirely. Use when a precise literature value is known and scaling from the default would be unreliable. <scope> is 'global' (every cell) or a tissue scope. set is applied after scale; using both on the same constant is an error.",
            notes="Same <constant_name> rule as the scale entry: use exactly a name from this model's 'constants' list; the prefix convention differs per model and cannot be inferred.",
            value_kind='scalar',
            dynamic_path=True,
            constraints=("<scope> must be one of: global, epicardialCells, mCells, endocardialCells, myocyte (ionicModelIO.C:182-189).",),
        ),
        ),
    ),
    "batched_integrator": build_group(
        defaults={"phases": frozenset({'solver'}), "applicable_when": {"ionicModel": ("AlievPanfilovcompactBatched", "BuenoOroviocompactBatched", "CourtemanchecompactBatched", "FabbricompactBatched", "GaurcompactBatched", "GrandicompactBatched", "PerisYaguecompactBatched", "StewartcompactBatched", "TNNPcompactBatched", "ToRORd_dynClcompactBatched", "TrovatocompactBatched", "TWorldcompactBatched")}},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.batchedIntegrator',
            description='Integration scheme for GPU/SOA batched models.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C',),
            value_kind='enum',
            enum_values=('euler', 'rushLarsen'),
            required=True,
            required_when={"ionicModel": ("AlievPanfilovcompactBatched", "BuenoOroviocompactBatched", "CourtemanchecompactBatched", "FabbricompactBatched", "GaurcompactBatched", "GrandicompactBatched", "PerisYaguecompactBatched", "StewartcompactBatched", "TNNPcompactBatched", "ToRORd_dynClcompactBatched", "TrovatocompactBatched", "TWorldcompactBatched")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.batchedSubsteps',
            description='Number of substeps for batched ODE integration.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.C',),
            value_kind='integer',
            required=True,
            typical_value='50',
            required_when={"ionicModel": ("AlievPanfilovcompactBatched", "BuenoOroviocompactBatched", "CourtemanchecompactBatched", "FabbricompactBatched", "GaurcompactBatched", "GrandicompactBatched", "PerisYaguecompactBatched", "StewartcompactBatched", "TNNPcompactBatched", "ToRORd_dynClcompactBatched", "TrovatocompactBatched", "TWorldcompactBatched")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.batchedParallelCells',
            description='Enable multithreaded cell loop execution for batched models.',
            source_refs=('src/ionicModels/ionicModel/batchedIonicModel.H',),
            value_kind='boolean',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.batchedParallelMinCells',
            description='Minimum cell threshold to trigger parallel execution if batchedParallelCells is true.',
            source_refs=('src/ionicModels/ionicModel/batchedIonicModel.H',),
            value_kind='integer',
            typical_value='256',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.storeBatchedAlgebraics',
            description='Force storing volatile algebraic states in memory for export/debug.',
            source_refs=('src/ionicModels/ionicModel/batchedIonicModel.H',),
            value_kind='boolean',
        ),
        ),
    ),
    "ode_solver_passthrough": build_group(
        defaults={"phases": frozenset({'solver'}), "applicable_when": {"myocardiumSolver": ("monodomainSolver", "bidomainSolver", "singleCellSolver")}},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.solver',
            description="ODE solver selector passed through to OpenFOAM's ODESolver factory.",
            source_refs=('src/ionicModels/ionicModel/ionicModel.H', 'src/activeTensionModels/GoktepeKuhl/GoktepeKuhl.C', 'src/activeTensionModels/NashPanfilov/NashPanfilov.C'),
            notes='The repository source shows pass-through to ODESolver::New(*this, dict_). Additional ODESolver-specific keys may exist beyond the commonly used entries listed here.',
            value_kind='enum',
            enum_values=('RKF45', 'Euler'),
            required=True,
            typical_value='RKF45',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.maxSteps',
            description='Maximum internal ODE steps allowed per macro time step.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.H',),
            notes='Pass-through key; commonly used in repository tutorials.',
            value_kind='integer',
            required=True,
            typical_value='1000',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.absTol',
            description='Absolute tolerance passed through to adaptive ODE solvers.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.H',),
            notes='Pass-through key; commonly used in repository tutorials.',
            value_kind='scalar',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.relTol',
            description='Relative tolerance passed through to adaptive ODE solvers.',
            source_refs=('src/ionicModels/ionicModel/ionicModel.H',),
            notes='Pass-through key; commonly used in repository tutorials.',
            value_kind='scalar',
        ),
        ),
    ),
    "single_cell_stimulus": build_group(
        defaults={"phases": frozenset({'stimulus'}), "source_refs": ("src/genericWriter/stimulusIO.C",), "applicable_when": {"myocardiumSolver": ("singleCellSolver",)}},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.stim_start',
            description='Start time for the S1/S2 stimulus protocol.',
            value_kind='scalar',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            unit='s',
            typical_value='0.0',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.stim_period_S1',
            description='S1 pacing cycle length.',
            value_kind='scalar',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            unit='s',
            typical_value='1.0',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.stim_duration',
            description='Pulse duration for both S1 and S2 stimuli.',
            value_kind='scalar',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            unit='s',
            typical_value='1.0',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.stim_amplitude',
            description='Stimulus amplitude for the S1/S2 protocol.',
            notes='Magnitude is model-class dependent. Full ionic models (TNNP, ORd, Grandi, Courtemanche, Fabbri, ...) use values around the typical_value below in pA. Phenomenological models (AlievPanfilov, BuenoOrovio) use dimensionless scaled values around 0.4-1.0; see ionic_model_catalog.IonicModelEntry.model_type to detect this case before using typical_value verbatim.',
            value_kind='scalar',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            typical_value='60',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.nstim1',
            description='Number of S1 pulses.',
            value_kind='integer',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            typical_value='3',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.stim_period_S2',
            description='S2 pacing cycle length.',
            value_kind='scalar',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            typical_value='0',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.singleCellStimulus.nstim2',
            description='Number of S2 pulses.',
            value_kind='integer',
            required=True,
            constraints=('Required when myocardiumSolver=singleCellSolver.',),
            typical_value='0',
            required_when={"myocardiumSolver": "singleCellSolver"},
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        ),
    ),
    "monodomain": build_group(
        defaults={},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductivitySource',
            phases=frozenset({'physics'}),
            description='Select whether myocardial conductivity is read from canonical disk fields or from tensor literals in this dictionary.',
            source_refs=('src/electroModels/core/conductivityFieldIO.C',),
            value_kind='enum',
            enum_values=('field', 'uniform'),
            required=True,
            constraints=('Spatial solvers use fixed field names: Conductivity for monodomain/eikonal and ConductivityIntracellular plus ConductivityExtracellular for bidomain.',),
            typical_value='uniform',
            applicable_when={"myocardiumSolver": ("monodomainSolver", "eikonalSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductivity',
            phases=frozenset({'physics'}),
            description='Monodomain conductivity tensor.',
            source_refs=('src/electroModels/myocardiumModels/monodomainSolver/monodomainSolver.C', 'src/electroModels/electroDomains/myocardiumDomain/eikonalMyocardiumDomain.C'),
            notes='Tensor entries are best overridden with a full OpenFOAM literal string.',
            value_kind='dimensioned_tensor_literal',
            required=True,
            constraints=('Required only when conductivitySource=uniform for monodomainSolver and eikonalSolver.',),
            unit='S/m',
            typical_value='[-1 -3 3 0 0 2 0] (0.1334 0 0 0.01761 0 0.01761)',
            required_when={"conductivitySource": "uniform"},
            applicable_when={"myocardiumSolver": ("monodomainSolver", "eikonalSolver"), "conductivitySource": "uniform"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.chi',
            phases=frozenset({'physics'}),
            description='Surface-to-volume ratio.',
            source_refs=('src/electroModels/myocardiumModels/monodomainSolver/monodomainSolver.C', 'src/electroModels/electroDomains/myocardiumDomain/eikonalMyocardiumDomain.C'),
            value_kind='scalar',
            required=True,
            constraints=('Required for monodomainSolver and bidomainSolver; not used by singleCellSolver.',),
            unit='1/m',
            typical_value='140000',
            required_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.cm',
            phases=frozenset({'physics'}),
            description='Membrane capacitance.',
            source_refs=('src/electroModels/myocardiumModels/monodomainSolver/monodomainSolver.C', 'src/electroModels/electroDomains/myocardiumDomain/eikonalMyocardiumDomain.C'),
            value_kind='scalar',
            required=True,
            constraints=('Required for monodomainSolver and bidomainSolver; not used by singleCellSolver.',),
            unit='F/m²',
            typical_value='0.01',
            required_when={"myocardiumSolver": ("monodomainSolver", "bidomainSolver")},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMin',
            phases=frozenset({'stimulus'}),
            description='Single-box minimum corner for PDE stimulus application.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='vector3',
            constraints=('Mutually exclusive with stimulusLocationMinList.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMinList',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMax',
            phases=frozenset({'stimulus'}),
            description='Single-box maximum corner for PDE stimulus application.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='vector3',
            constraints=('Mutually exclusive with stimulusLocationMaxList.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMaxList',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMinList',
            phases=frozenset({'stimulus'}),
            description='Per-box minimum corners for multi-region PDE stimulation.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='vector3_list',
            constraints=('Mutually exclusive with stimulusLocationMin.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMin',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMaxList',
            phases=frozenset({'stimulus'}),
            description='Per-box maximum corners for multi-region PDE stimulation.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='vector3_list',
            constraints=('Mutually exclusive with stimulusLocationMax.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusLocationMax',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusStartTime',
            phases=frozenset({'stimulus'}),
            description='Shared start time for all PDE stimulus boxes.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='scalar',
            constraints=('Mutually exclusive with stimulusStartTimeList.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusStartTimeList',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusStartTimeList',
            phases=frozenset({'stimulus'}),
            description='Per-box start times for PDE stimulus boxes.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='scalar_list',
            constraints=('Mutually exclusive with stimulusStartTime.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusStartTime',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusDuration',
            phases=frozenset({'stimulus'}),
            description='Shared duration for all PDE stimulus boxes.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            notes='DimensionedScalar-style values are best passed as a full literal string.',
            value_kind='dimensioned_scalar_literal',
            constraints=('Mutually exclusive with stimulusDurationList.',),
            unit='s',
            typical_value='0.002',
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusDurationList',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusDurationList',
            phases=frozenset({'stimulus'}),
            description='Per-box durations for PDE stimulus boxes.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='scalar_list',
            constraints=('Mutually exclusive with stimulusDuration.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusDuration',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusIntensity',
            phases=frozenset({'stimulus'}),
            description='Shared current density for all PDE stimulus boxes.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            notes='DimensionedScalar-style values are best passed as a full literal string.',
            value_kind='dimensioned_scalar_literal',
            constraints=('Mutually exclusive with stimulusIntensityList.',),
            unit='A/m³',
            typical_value='50000',
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusIntensityList',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusIntensityList',
            phases=frozenset({'stimulus'}),
            description='Per-box current densities for PDE stimulus boxes.',
            source_refs=('src/genericWriter/stimulusIO.C',),
            value_kind='scalar_list',
            constraints=('Mutually exclusive with stimulusIntensity.',),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.externalStimulus.stimulusIntensity',),
            forbidden_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.verificationModel.type',
            phases=frozenset({'solver'}),
            description='Optional myocardium-side verification hook selector.',
            source_refs=('src/electroModels/core/verificationModels/electroVerificationModel.C', 'src/verificationModels/monodomainVerification/manufacturedFDAMonodomainVerifier.H', 'src/verificationModels/bidomainVerification/manufacturedFDABidomainVerifier.H', 'src/verificationModels/bathBidomainVerification/manufacturedFDABathBidomainVerifier.H', 'src/verificationModels/eikonalVerification/manufacturedEikonalVerifier.H', 'src/verificationModels/monodomainVerification/manufacturedAnisotropicMonodomainVerifier.H'),
            value_kind='enum',
            enum_values=('manufacturedFDAMonodomainVerifier', 'manufacturedFDABidomainVerifier', 'manufacturedFDABathBidomainVerifier', 'manufacturedEikonalVerifier', 'manufacturedAnisotropicMonodomainVerifier'),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.verificationModel.fdaBathVariant',
            source_refs=('src/verificationModels/bathBidomainVerification/manufacturedFDABathBidomainVerifier.C',),
            phases=frozenset({'physics'}),
            description=(
                'Which of the two FDA bidomain-with-bath boundary variants of section 3.3 '
                'is being verified. groundElectrode applies a Dirichlet phiE = 0 at x = -1 '
                'with a surface current +alpha at x = 2. electrodePair applies -alpha at '
                'x = -1 and +alpha at x = 2 with no ground, whose integral over the boundary '
                'vanishes so the problem stays solvable while phiE floats. The key also '
                'selects the error metric: with an electrode pair the exact phiE carries an '
                'arbitrary C(t), so phiE and phiI are compared after removing their '
                'volume-weighted means. Configuring the boundary conditions and the metric '
                'from one key prevents a case being solved as one variant and measured as '
                'the other.'
            ),
            value_kind='enum',
            enum_values=('groundElectrode', 'electrodePair'),
            typical_value='groundElectrode',
            applicable_when={"$ELECTRO_MODEL_COEFFS.verificationModel.type": ("manufacturedFDABathBidomainVerifier",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.verificationModel.writeErrorField',
            phases=frozenset({'solver'}),
            description='Writes the per-cell signed activation-time error field to disk each write interval, for correlating error against local mesh quality.',
            source_refs=('src/verificationModels/eikonalVerification/manufacturedEikonalVerifier.C',),
            value_kind='boolean',
            typical_value='false',
            applicable_when={"$ELECTRO_MODEL_COEFFS.verificationModel.type": ("manufacturedEikonalVerifier",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.verificationModel.alpha',
            phases=frozenset({'physics'}),
            description='Temporal scaling parameter for the manufactured analytical solution.',
            source_refs=('src/verificationModels/monodomainVerification/manufacturedFDAMonodomainVerifier.C',),
            value_kind='scalar',
            typical_value='0.01',
            applicable_when={"$ELECTRO_MODEL_COEFFS.verificationModel.type": ("manufacturedFDABathBidomainVerifier",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.verificationModel.k',
            phases=frozenset({'physics'}),
            description='Wave vector parameter for the bath-bidomain manufactured analytical solution.',
            source_refs=('src/verificationModels/bathBidomainVerification/manufacturedFDABathBidomainVerifier.C',),
            notes='Only manufacturedFDABathBidomainVerifier reads k from verificationModel (manufacturedFDABathBidomainVerifier.C:84-86,113). manufacturedFDABidomainVerifier reads it from the manufacturedBidomain sub-dict instead -- see $ELECTRO_MODEL_COEFFS.manufacturedBidomain.k. manufacturedFDAMonodomainVerifier reads no k at all.',
            value_kind='scalar',
            applicable_when={"$ELECTRO_MODEL_COEFFS.verificationModel.type": ("manufacturedFDABathBidomainVerifier",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.verificationModel.groundElectrode',
            phases=frozenset({'physics'}),
            description='Analytically pins a ground Dirichlet reference for bath-bidomain manufactured models.',
            source_refs=('src/verificationModels/bathBidomainVerification/manufacturedFDABathBidomainVerifier.C',),
            value_kind='boolean',
            typical_value='true',
            applicable_when={"$ELECTRO_MODEL_COEFFS.verificationModel.type": ("manufacturedFDABathBidomainVerifier",)},
        ),
        ),
    ),
    "bath_potential_domain": build_group(
        defaults={"source_refs": ("src/electroModels/electroDomains/extracellularPotentialDomain/extracellularPotentialDomain.C",), "applicable_when": {"$bathPotentialDomain_configured": True}},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.bathCellZones',
            phases=frozenset({'physics', 'anatomy'}),
            description='Cell zones treated as conductive bath, torso, or organ tissue in the unified extracellular-potential domain.',
            value_kind='word_list',
            required=True,
            constraints=('Required when bathPotentialDomain is configured.',),
            required_when={"$bathPotentialDomain_configured": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.bathConductivityField',
            phases=frozenset({'physics'}),
            description='Volume field name containing bath/organ conductivity values.',
            value_kind='word',
            typical_value='bodyAndOrgansConductivity',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.phiEReferenceValue',
            phases=frozenset({'physics'}),
            description='Extracellular-potential reference value used when a reference cell is applied.',
            value_kind='scalar',
            unit='V',
            typical_value='0.0',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.reportSetup',
            phases=frozenset({'solver'}),
            description='Switch that logs heart/bath mesh wiring and boundary setup.',
            value_kind='boolean',
            typical_value='false',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.phiERefPoint',
            phases=frozenset({'physics'}),
            description='Point used to locate the reference cell for pure-Neumann extracellular-potential boundaries.',
            value_kind='vector3',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.groundPatches.<patch>',
            phases=frozenset({'physics'}),
            description='Dirichlet ground-patch value map for extracellular potential.',
            value_kind='scalar',
            dynamic_path=True,
            constraints=(
                'A given <patch> key is mutually exclusive with the same '
                '<patch> key under surfaceCurrentPatches -- '
                'extracellularPotentialDomain.C rejects a patch listed in '
                'both. Switching a variant/override that moves a patch '
                'between the two maps must remove it from the old map, not '
                'just add it to the new one (see fdaBathVariant callers).',
            ),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.bathPotentialDomain.surfaceCurrentPatches.<patch>',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.surfaceCurrentPatches.<patch>',
            phases=frozenset({'physics', 'stimulus'}),
            description='Neumann surface-current patch map; values are scalar surface-current values.',
            value_kind='scalar',
            dynamic_path=True,
            constraints=(
                'A given <patch> key is mutually exclusive with the same '
                '<patch> key under groundPatches -- '
                'extracellularPotentialDomain.C rejects a patch listed in '
                'both. Switching a variant/override that moves a patch '
                'between the two maps must remove it from the old map, not '
                'just add it to the new one (see fdaBathVariant callers).',
            ),
            mutually_exclusive_with=('$ELECTRO_MODEL_COEFFS.bathPotentialDomain.groundPatches.<patch>',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPotentialDomain.interfaceConductivityInterpolation',
            phases=frozenset({'physics'}),
            description='Face-interpolation scheme for the conductivity across the heart/bath interface. Both are harmonic means, which keep the normal current continuous; distanceWeightedHarmonic (default) additionally weights by the face interpolation factor and is the scheme the reported bath results use.',
            value_kind='enum',
            enum_values=('unweightedHarmonic', 'distanceWeightedHarmonic'),
            typical_value='distanceWeightedHarmonic',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.bathPredictorCorrector',
            source_refs=('src/electroModels/core/advanceSchemes/staggered/staggeredElectrophysicsAdvanceScheme.C',),
            phases=frozenset({'solver'}),
            description='Whether to predict Vm, update the global extracellular potential phiE from that predictor, and correct Vm within each physical step. Defaults to true. When false, the step updates phiE and then solves Vm with phiE held fixed. Neither setting advances the ionic state or physical time twice.',
            value_kind='boolean',
            typical_value='true',
            constraints=('Only applicable to bidomainSolver runs with a bathPotentialDomain configured.',),
        ),
        ),
    ),
    "eikonal_diffusion": build_group(
        defaults={"source_refs": ("src/electroModels/electroDomains/myocardiumDomain/eikonalMyocardiumDomain.C",)},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.eikonalAdvectionDiffusionApproach',
            phases=frozenset({'physics'}),
            description='Toggle between the advection-diffusion and deferred-correction forms.',
            value_kind='boolean',
            required=True,
            constraints=('Required when myocardiumSolver=eikonalSolver.',),
            required_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.stimulusLocationMin',
            phases=frozenset({'stimulus'}),
            description='Minimum corner of the eikonal stimulus bounding box.',
            value_kind='vector3',
            required=True,
            constraints=('Required when myocardiumSolver=eikonalSolver.',),
            required_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.stimulusLocationMax',
            phases=frozenset({'stimulus'}),
            description='Maximum corner of the eikonal stimulus bounding box.',
            value_kind='vector3',
            required=True,
            constraints=('Required when myocardiumSolver=eikonalSolver.',),
            required_when={"myocardiumSolver": "eikonalSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.c0',
            phases=frozenset({'physics'}),
            description='Wave-speed parameter for the eikonal formulation.',
            value_kind='scalar',
            required=True,
            constraints=('Required when myocardiumSolver=eikonalSolver.',),
            required_when={"myocardiumSolver": "eikonalSolver"},
        ),
        ),
    ),
    "ecg": build_group(
        defaults={},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.electrodePositions.<electrode>',
            phases=frozenset({'physics'}),
            description='Shared electrode position vector [m] inherited by ECG domain entries unless overridden.',
            source_refs=('src/electroModels/core/system/electrophysicsSystemBuilder.C', 'src/electroModels/electroDomains/ecgDomain/ecgDomain.C'),
            value_kind='vector3',
            dynamic_path=True,
            constraints=('Only applicable when ecgDomains block is present in electroProperties.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.ecgSolver',
            phases=frozenset({'physics'}),
            description="ECG solver selector within the ecgDomains sub-dictionary. pseudoECG: dipole approximation, works with any PDE solver. torsoECG: reads phiE from a bath/torso domain, requires bidomainSolver + bathPotentialDomain. eikonalECG: fast activation-time surrogate using precomputed tissue templates, requires eikonalSolver; a 'sampling' sub-dictionary (start, end, deltaT) is mandatory.",
            source_refs=('src/electroModels/electroDomains/ecgDomain/ecgSolver.C', 'src/electroModels/ecgModels/eikonalECG/eikonalECG.C'),
            value_kind='enum',
            enum_values=('pseudoECG', 'torsoECG', 'eikonalECG'),
            dynamic_path=True,
            constraints=("Only applicable when ecgDomains block is present in electroProperties. torsoECG requires bathPotentialDomain with bidomainSolver. eikonalECG requires eikonalSolver and a mandatory 'sampling' sub-dict.",),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.sigmaExtracellular',
            phases=frozenset({'physics'}),
            description='Extracellular conductivity fallback value used by pseudoECG solver if a 3D tensor field is not available.',
            source_refs=('src/electroModels/ecgModels/pseudoECGSolver/pseudoECGSolver.H',),
            value_kind='scalar',
            dynamic_path=True,
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.sampling.start',
            phases=frozenset({'physics'}),
            description='Start of the Vm-response interpolation window [s] for eikonalECG. Usually 0. The tissue template lookup begins at this time.',
            source_refs=('src/electroModels/ecgModels/eikonalECG/eikonalECG.C',),
            dynamic_path=True,
            required=True,
            unit='s',
            typical_value='0',
            applicable_when={"$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.ecgSolver": "eikonalECG"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.sampling.end',
            phases=frozenset({'physics'}),
            description='End of the Vm-response interpolation window [s] for eikonalECG. Must be >= action potential duration. Human ventricular AP: ~0.3–0.5 s. Must not exceed tissue template duration (~1.0 s). Setting this shorter than APD truncates repolarisation in the ECG.',
            source_refs=('src/electroModels/ecgModels/eikonalECG/eikonalECG.C',),
            dynamic_path=True,
            required=True,
            unit='s',
            typical_value='0.5',
            applicable_when={"$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.ecgSolver": "eikonalECG"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.sampling.deltaT',
            phases=frozenset({'physics'}),
            description='Time step of the Vm-response interpolation [s] for eikonalECG. Controls ECG output resolution; independent of the solver deltaT. Typical range: 0.001–0.005 s. Finer than 0.001 s has no benefit as the tissue templates are sampled at 0.1 ms resolution.',
            source_refs=('src/electroModels/ecgModels/eikonalECG/eikonalECG.C',),
            dynamic_path=True,
            required=True,
            unit='s',
            typical_value='0.005',
            applicable_when={"$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.ecgSolver": "eikonalECG"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.reportElectrodeLookup',
            phases=frozenset({'solver'}),
            description='Switch controlling torsoECG electrode-to-cell lookup logging.',
            source_refs=('src/electroModels/ecgModels/torsoECG/torsoECG.C',),
            value_kind='boolean',
            dynamic_path=True,
            constraints=('Only applicable when ecgSolver=torsoECG.',),
            typical_value='true',
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.manufactured.enabled',
            phases=frozenset({'physics'}),
            description='Enable manufactured pseudo-ECG verification for the selected ECG domain.',
            source_refs=('src/verificationModels/ecgVerification/pseudoECGManufacturedVerifier.C',),
            value_kind='boolean',
            dynamic_path=True,
            constraints=('Only applicable when ecgDomains block is present in electroProperties.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.manufactured.dimension',
            phases=frozenset({'physics'}),
            description='Dimensional selector used by the manufactured pseudo-ECG reference.',
            source_refs=('src/verificationModels/ecgVerification/pseudoECGManufacturedVerifier.C',),
            value_kind='enum',
            enum_values=('1D', '2D', '3D'),
            dynamic_path=True,
            constraints=('Only applicable when ecgDomains block is present in electroProperties.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.manufactured.referenceQuadratureOrder',
            phases=frozenset({'physics'}),
            description='Quadrature order used for the manufactured pseudo-ECG reference integral.',
            source_refs=('src/verificationModels/ecgVerification/pseudoECGManufacturedVerifier.C',),
            value_kind='integer',
            dynamic_path=True,
            constraints=('Only applicable when ecgDomains block is present in electroProperties.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.manufactured.checkQuadratureOrders',
            phases=frozenset({'physics'}),
            description='List of quadrature orders used to compare manufactured pseudo-ECG reference convergence. Default when omitted: (6 12 24 48), set at pseudoECGManufacturedVerifier.C:363-367.',
            source_refs=('src/verificationModels/ecgVerification/pseudoECGManufacturedVerifier.C',),
            value_kind='label_list',
            dynamic_path=True,
            constraints=('Only applicable when ecgDomains block is present in electroProperties.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.electrodePositions.<electrode>',
            phases=frozenset({'physics'}),
            description='Per-electrode position vector [m] in the ECG domain block.',
            source_refs=('src/electroModels/electroDomains/ecgDomain/ecgDomain.C',),
            notes='The driver can update existing electrode entries but does not insert new electrode names.',
            value_kind='vector3',
            dynamic_path=True,
            constraints=('Only applicable when ecgDomains block is present in electroProperties.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.ecgDomains.<name>.coupling.electroDomainCoupler',
            phases=frozenset({'physics'}),
            description='Optional ECG-domain coupling selector dispatched through electroDomainCoupler.',
            source_refs=('src/electroModels/core/system/electrophysicsSystemBuilder.C', 'src/electroModels/electroCouplers/electroDomainCoupler.C'),
            value_kind='enum',
            enum_values=('reactionDiffusionPvjCoupler', 'eikonalPvjCoupler', 'eikonalMonodomainPvjCoupler'),
            dynamic_path=True,
            constraints=('Only applicable when an ECG domain declares a coupling block.',),
            applicable_when={"$ecgDomains_present": True},
        ),
        ),
    ),
    "bidomain": build_group(
        defaults={"phases": frozenset({'physics'}), "source_refs": ("src/electroModels/myocardiumModels/bidomainSolver/bidomainSolver.C",)},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductivityIntracellular',
            description='Intracellular conductivity tensor for the bidomain formulation.',
            notes='Tensor entries are best overridden with a full OpenFOAM literal string.',
            value_kind='dimensioned_tensor_literal',
            required=True,
            constraints=('Required only when conductivitySource=uniform for bidomainSolver.',),
            unit='S/m',
            typical_value='[-1 -3 3 0 0 2 0] (0.1334 0 0 0.01761 0 0.01761)',
            required_when={"conductivitySource": "uniform"},
            applicable_when={"myocardiumSolver": "bidomainSolver", "conductivitySource": "uniform"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductivityExtracellular',
            description='Extracellular conductivity tensor for the bidomain formulation.',
            notes='Tensor entries are best overridden with a full OpenFOAM literal string.',
            value_kind='dimensioned_tensor_literal',
            required=True,
            constraints=('Required only when conductivitySource=uniform for bidomainSolver.',),
            unit='S/m',
            typical_value='[-1 -3 3 0 0 2 0] (0.2668 0 0 0.03521 0 0.03521)',
            required_when={"conductivitySource": "uniform"},
            applicable_when={"myocardiumSolver": "bidomainSolver", "conductivitySource": "uniform"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.phiERefPoint',
            description='Point [m] used to locate the cell that pins the extracellular potential reference. The bidomain φE equation has pure Neumann boundary conditions, leaving φE determined only up to an additive constant — one cell must be clamped to break the indeterminacy. Monodomain solves only Vm with mixed BCs and does not need a reference point.',
            notes='Applies to plain bidomain and bath-bidomain alike — both run on bidomainSolver, only the extracellular domain (heart-only vs heart+bath) differs. If the supplied point falls outside the mesh the solver falls back to a default cell.',
            value_kind='vector3',
            required=True,
            constraints=('Required for bidomainSolver.',),
            typical_value='(0 0 0)',
            required_when={"myocardiumSolver": "bidomainSolver"},
            applicable_when={"myocardiumSolver": "bidomainSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.phiEReferenceValue',
            description='Value of the extracellular potential [V] at the reference cell located by phiERefPoint. Optional — defaults to 0 V when omitted, which is the standard choice for ungrounded bidomain solves.',
            value_kind='scalar',
            unit='V',
            typical_value='0',
            applicable_when={"myocardiumSolver": "bidomainSolver"},
        ),
        ),
    ),
    "conduction_system": build_group(
        defaults={},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.conductionSystemDomain',
            phases=frozenset({'physics', 'anatomy'}),
            description='Conduction system domain model selector (sub-dictionary within conductionNetworkDomains). Used exclusively in Purkinje/1D pipelines.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='enum',
            enum_values=('purkinjeGraphModel',),
            dynamic_path=True,
            constraints=('Only applicable when conductionNetworkDomains block is present.',),
            applicable_when={"$conductionNetworkDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.graphFile',
            phases=frozenset({'physics', 'anatomy'}),
            description="REQUIRED: Name of the graph file in constant/ directory (e.g., 'purkinjeGraph'). The graph file must contain 'edges', 'points', 'pvjNodes', 'pvjLocations' dictionaries/lists.",
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='word',
            dynamic_path=True,
            required=True,
            constraints=('Required when a Purkinje graph is configured.',),
            required_when={"$conductionNetworkDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.conductionSystemSolver',
            phases=frozenset({'physics'}),
            description='1D graph solver used within the conduction network domain. Default is monodomain1DSolver.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemSolver.C', 'src/electroModels/conductionSystemModels/monodomain1DSolver/monodomain1DSolver.H', 'src/electroModels/conductionSystemModels/eikonalSolver1D/eikonalSolver1D.H'),
            value_kind='enum',
            enum_values=('monodomain1DSolver', 'eikonalSolver1D', 'restitutionEikonalSolver1D'),
            dynamic_path=True,
            constraints=('monodomain1DSolver valid only with monodomainSolver myocardium; eikonalSolver1D valid only with eikonalSolver myocardium.',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.useEdgeConductance',
            phases=frozenset({'physics'}),
            description='If true, uses local edge conductances to scale conduction velocity in the eikonal solver.',
            source_refs=('src/electroModels/conductionSystemModels/restitutionEikonalSolver1D/restitutionEikonalSolver1D.C',),
            value_kind='boolean',
            dynamic_path=True,
            typical_value='true',
            applicable_when={"$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.conductionSystemSolver": ("restitutionEikonalSolver1D",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.referenceConductance',
            phases=frozenset({'physics'}),
            description='Reference conductance value used to normalize the edge conductances when scaling velocity.',
            source_refs=('src/electroModels/conductionSystemModels/restitutionEikonalSolver1D/restitutionEikonalSolver1D.C',),
            value_kind='scalar',
            dynamic_path=True,
            typical_value='1.0',
            applicable_when={"$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.conductionSystemSolver": ("restitutionEikonalSolver1D",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.apdNominal',
            phases=frozenset({'physics'}),
            description='Nominal Action Potential Duration [ms] for multi-beat restitution dynamics.',
            source_refs=('src/electroModels/conductionSystemModels/restitutionEikonalSolver1D/restitutionEikonalSolver1D.H',),
            value_kind='scalar',
            dynamic_path=True,
            applicable_when={"$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.conductionSystemSolver": ("restitutionEikonalSolver1D",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.escapeInterval',
            phases=frozenset({'physics'}),
            description='Funny current escape interval [ms] dictating spontaneous firing in absence of stimulus.',
            source_refs=('src/electroModels/conductionSystemModels/restitutionEikonalSolver1D/restitutionEikonalSolver1D.H',),
            value_kind='scalar',
            dynamic_path=True,
            applicable_when={"$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.conductionSystemSolver": ("restitutionEikonalSolver1D",)},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.ionicModel',
            phases=frozenset({'physics'}),
            description='Ionic model used for 1D Purkinje monodomain. Uses the same runtime selection table as the 3D myocardium solver. Stewart (human Purkinje) is the canonical choice for conduction system simulations.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C', 'src/ionicModels/ionicModel/ionicModel.C'),
            notes='Stewart is the canonical human Purkinje model. monodomainFDAManufactured/bidomainFDAManufactured are for verification only.',
            value_kind='enum',
            enum_values=('AlievPanfilov', 'BuenoOrovio', 'Courtemanche', 'Fabbri', 'Gaur', 'Grandi', 'Stewart', 'TNNP', 'ToRORd_dynCl', 'Trovato', 'monodomainFDAManufactured', 'bidomainFDAManufactured', 'AlievPanfilovcompactBatched', 'BuenoOroviocompactBatched', 'CourtemanchecompactBatched', 'FabbricompactBatched', 'GaurcompactBatched', 'GrandicompactBatched', 'PerisYaguecompactBatched', 'StewartcompactBatched', 'TNNPcompactBatched', 'ToRORd_dynClcompactBatched', 'TrovatocompactBatched', 'TWorldcompactBatched'),
            dynamic_path=True,
            constraints=('Required when conductionSystemSolver=monodomain1DSolver.',),
            required_when={"$conductionNetworkDomains_present": True},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.tissue',
            phases=frozenset({'physics'}),
            description='Tissue type for 1D Purkinje ionic model. Examples: epicardialCells, endocardialCells, mCells, myocyte.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C', 'src/ionicModels/ionicModel/ionicModel.H'),
            value_kind='enum',
            enum_values=('epicardialCells', 'endocardialCells', 'mCells', 'myocyte'),
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.rootStimulus.startTime',
            phases=frozenset({'stimulus'}),
            description='Start time [s] of the root-node stimulus applied to Purkinje node 0.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='scalar',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.rootStimulus.duration',
            phases=frozenset({'stimulus'}),
            description='Duration [s] of the root-node stimulus pulse.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='scalar',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.rootStimulus.intensity',
            phases=frozenset({'stimulus'}),
            description='Amplitude [A/m³] of the root-node stimulus current applied to Purkinje node 0.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='scalar',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.rootStimulus.node',
            phases=frozenset({'stimulus'}),
            description='Optional graph-node index that overrides the graph-file rootNode for the applied root stimulus.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='label',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.chi',
            phases=frozenset({'physics'}),
            description='Surface-to-volume ratio [1/m] for the 1D Purkinje monodomain equation.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='scalar',
            dynamic_path=True,
            unit='1/m',
            typical_value='140000',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.cm',
            phases=frozenset({'physics'}),
            description='Membrane capacitance [F/m²] for the 1D Purkinje monodomain equation.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='scalar',
            dynamic_path=True,
            unit='F/m²',
            typical_value='0.01',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.vm1DRest',
            phases=frozenset({'physics'}),
            description='Resting transmembrane potential [V] used to initialise the 1D Purkinje field. Default: -0.084 V.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='scalar',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.outputVariables.export',
            phases=frozenset({'solver'}),
            description="Word list of variables written to postProcessing/purkinjeNetwork.dat. Note the FLAT layout — this dict has 'export' and 'debug' directly inside outputVariables, with NO 'ionic' sub-block (unlike the myocardium-side outputVariables.ionic.export). Valid tokens are a hardcoded set: Vm, Iion, activationTime, IcouplingSource, IcouplingCurrent. Unknown tokens are silently dropped without a warning — see the if/else ladder in conductionSystemDomain.C. Default: (Vm IcouplingSource).",
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='word_list',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.conductionNetworkDomains.<name>.purkinjeGraphModelCoeffs.outputVariables.debug',
            phases=frozenset({'solver'}),
            description='Word list of variables printed to terminal every 10 time steps. Same flat layout and same valid-token set as the Purkinje outputVariables.export entry: Vm, Iion, activationTime, IcouplingSource, IcouplingCurrent. Default: empty.',
            source_refs=('src/electroModels/electroDomains/conductionSystemDomain/conductionSystemDomain.C',),
            value_kind='word_list',
            dynamic_path=True,
        ),
        ),
    ),
    "active_tension": build_group(
        defaults={"phases": frozenset({'physics'})},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.activeTensionModel',
            description="Active-tension model selector. Read as a flat word entry directly inside <solver>Coeffs — there is no 'activeTensionModel { ... }' sub-block in the real dicts. Currently only singleCellSolver constructs an activeTensionModel from electroProperties (electroProperties().found('activeTensionModel') / activeTensionModel::New(electroProperties(), ...) in singleCellSolver.C). The electro-mechanical coupling path reads the identically-named flat key from the separate electroMechanicalProperties file (sequentialElectroMechanical.C), which this catalog does not cover.",
            source_refs=('src/activeTensionModels/activeTensionModel/activeTensionModel.C', 'src/electroModels/myocardiumModels/singleCellSolver/singleCellSolver.C'),
            value_kind='enum',
            enum_values=('GoktepeKuhl', 'NashPanfilov', 'LandNiederer', 'GoktepeKuhlBatched', 'NashPanfilovBatched', 'LandNiedererBatched', 'ManufacturedElectromechanics'),
            constraints=('Only applicable for singleCellSolver.',),
            applicable_when={"myocardiumSolver": "singleCellSolver"},
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.couplingSignal',
            description='Coupling signal requested by the active-tension model. Flat sibling of activeTensionModel inside <solver>Coeffs, not nested under it.',
            source_refs=('src/activeTensionModels/GoktepeKuhl/GoktepeKuhl.C', 'src/activeTensionModels/NashPanfilov/NashPanfilov.C'),
            value_kind='enum',
            enum_values=('Vm',),
            constraints=('Only applicable when activeTensionModel is configured.',),
            applicable_when={"activeTensionModel": ("GoktepeKuhl", "NashPanfilov")},
        ),
        ),
    ),
    "domain_couplings": build_group(
        defaults={"phases": frozenset({'physics'})},
        entries=(
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.electroDomainCoupler',
            description='Coupling model selector for domain-to-domain interactions (e.g., Purkinje-to-myocardium). Used only when multiple domains are present.',
            source_refs=('src/electroModels/electroCouplers/electroDomainCoupler.C', 'src/electroModels/electroCouplers/pvjCoupler/reactionDiffusion/reactionDiffusionPvjCoupler.C', 'src/electroModels/electroCouplers/pvjCoupler/eikonalMonodomain/eikonalMonodomainPvjCoupler.C'),
            value_kind='enum',
            enum_values=('reactionDiffusionPvjCoupler', 'eikonalPvjCoupler', 'eikonalMonodomainPvjCoupler'),
            dynamic_path=True,
            constraints=('reactionDiffusionPvjCoupler valid only with monodomainSolver+monodomain1DSolver; eikonalPvjCoupler valid only with eikonalSolver+eikonalSolver (1D).',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.conductionNetworkDomain',
            description='REQUIRED: Name of the conductionNetworkDomains entry this coupling targets. Must match a key in conductionNetworkDomains.',
            source_refs=('src/electroModels/core/system/electrophysicsSystemBuilder.C',),
            value_kind='word',
            dynamic_path=True,
            required=True,
            constraints=('Must match a key in conductionNetworkDomains.',),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.rPvj',
            description='Junction resistance [Ω·m²] per unit surface area. Used by reactionDiffusionPvjCoupler for monodomain coupling. Example: 500.0 Ω·m².',
            source_refs=('src/electroModels/electroCouplers/pvjCoupler/reactionDiffusion/reactionDiffusionPvjCoupler.C',),
            value_kind='scalar',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.pvjRadius',
            description='Sphere radius [m] around each PVJ used to identify 3D cells for coupling. Default: 0.5e-3 m.',
            source_refs=('src/electroModels/electroCouplers/pvjCoupler/pvjCoupler.C',),
            value_kind='scalar',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.pvjKernel',
            description='Interpolation kernel used when mapping 1D Purkinje junctions to 3D myocardium. Options: uniform, gaussian, linear. Default: uniform.',
            source_refs=('src/electroModels/electroCouplers/pvjCoupler/pvjCoupler.C',),
            value_kind='enum',
            enum_values=('uniform', 'gaussian', 'linear'),
            dynamic_path=True,
            typical_value='uniform',
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.pvjCouplingScheme',
            description="PVJ source treatment for reactionDiffusionPvjCoupler: 'explicit' injects the full coupling current as a source, while 'implicit' splits the tissue-voltage part onto the myocardium Vm matrix diagonal. Default: explicit.",
            source_refs=('src/electroModels/electroCouplers/pvjCoupler/reactionDiffusion/reactionDiffusionPvjCoupler.C',),
            value_kind='enum',
            enum_values=('explicit', 'implicit'),
            dynamic_path=True,
            typical_value='explicit',
            constraints=("Only applicable to reactionDiffusionPvjCoupler.",),
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.debugCoupling',
            description='Outputs verbose logging about PVJ coupling weights and mappings.',
            source_refs=('src/electroModels/electroCouplers/electroDomainCoupler.C',),
            value_kind='boolean',
            dynamic_path=True,
        ),
        DictEntry(
            driver_path='$ELECTRO_MODEL_COEFFS.domainCouplings.<name>.couplingMode',
            description="Coupling direction: 'unidirectional' (Purkinje→myocardium only) or 'bidirectional' (both ways). REQUIRED -- pvjCoupler.C:91 uses get<word>, so omitting it is a fatal error, not a default.",
            source_refs=('src/electroModels/electroCouplers/pvjCoupler/pvjCoupler.H',),
            value_kind='enum',
            enum_values=('unidirectional', 'bidirectional'),
            dynamic_path=True,
        ),
        ),
    ),
}
