#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf case.foam postProcessing constant/dualMesh
(cd 0 && rm -f el en et  alphaRadiansf elf enf etf t)

# Replace t field
\cp 0/org/t 0/t
