#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf case.foam postProcessing
(cd 0 && rm -f alphaRadians dxduHat dxdvHat rs v t alpha dxdu dxdv f0 rl s0 u z)

# Replace t field
cp 0/org/t 0/t
