#!/usr/bin/env python3
#----------------------------------------------------------------------------#
# License
#     This file is part of cardiacFoam.
#
#     cardiacFoam is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation, either version 3 of the License, or (at your
#     option) any later version.
#
#     cardiacFoam is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with cardiacFoam.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     export-capability-seams
#
# Description
#     Renders the plugin capability seam table from the structured fields in
#     each capability Protocol's docstring in core/plugin_capabilities.py.
#
#     The docstrings are the single source of truth: there is no parallel
#     registry to drift. Each capability Protocol ends with four fields --
#     :adapts:, :consumed-by:, :fallback:, :status: -- whose meaning is
#     documented on PluginCapabilities itself.
#
#     Run with --check to verify the committed ARCHITECTURE.md table matches a
#     fresh render; the conformance test uses that mode.
#
# Author
#     Simao Nieto de Castro, UCD.
#----------------------------------------------------------------------------#

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

ARCHITECTURE = REPO_ROOT / "ARCHITECTURE.md"
BEGIN_MARKER = "<!-- BEGIN GENERATED: capability-seams -->"
END_MARKER = "<!-- END GENERATED: capability-seams -->"

FIELD_NAMES = ("adapts", "consumed-by", "fallback", "status")
_FIELD_RE = re.compile(r"^\s*:(?P<name>[a-z-]+):\s*(?P<value>.+?)\s*$", re.MULTILINE)


@dataclass(frozen=True)
class Seam:
    field: str
    protocol: str
    adapts: str
    consumed_by: str
    fallback: str
    status: str


def parse_fields(docstring: str | None) -> dict[str, str]:
    """Extract the four structured fields from a capability docstring.

    Continuation lines (an indented line following a field, not itself a
    field) are folded into the preceding field's value, so a long
    ``:consumed-by:`` list may wrap.
    """
    if not docstring:
        return {}
    fields: dict[str, str] = {}
    current: str | None = None
    for line in docstring.splitlines():
        match = _FIELD_RE.match(line)
        if match:
            current = match.group("name")
            fields[current] = match.group("value")
            continue
        stripped = line.strip()
        if current and stripped and line[:1].isspace():
            fields[current] = f"{fields[current]} {stripped}"
            continue
        current = None
    return fields


def collect_seams() -> list[Seam]:
    """Read the seams in the order PluginCapabilities declares its fields."""
    from openfoam_driver.core import plugin_capabilities as pc

    seams: list[Seam] = []
    for field_name, annotation in pc.PluginCapabilities.__annotations__.items():
        protocol = (
            annotation
            if isinstance(annotation, str)
            else getattr(annotation, "__name__", str(annotation))
        )
        protocol_cls = getattr(pc, protocol, None)
        fields = parse_fields(getattr(protocol_cls, "__doc__", None))
        seams.append(
            Seam(
                field=field_name,
                protocol=protocol,
                adapts=fields.get("adapts", ""),
                consumed_by=fields.get("consumed-by", ""),
                fallback=fields.get("fallback", ""),
                status=fields.get("status", ""),
            )
        )
    return seams


def _cell(value: str) -> str:
    if not value:
        return "—"
    return value.replace("|", r"\|")


def _code_list(value: str) -> str:
    """Render a comma-separated field as inline code, one item per entry."""
    if not value or value.strip() == "none":
        return "none"
    items = [item.strip() for item in value.split(",") if item.strip()]
    return ", ".join(f"`{_cell(item)}`" for item in items)


def render(seams: list[Seam]) -> str:
    lines = [
        BEGIN_MARKER,
        "",
        "<!-- Generated by scripts/export-capability-seams.py -- do not edit by",
        "     hand. The source of truth is the structured field block in each",
        "     capability Protocol's docstring in core/plugin_capabilities.py. -->",
        "",
        "`SolverPlugin` (and `SolverPluginV2`, plus the optional",
        "`SolverPluginOptionalHooks`) in `core/plugin_interface.py` is the **public**",
        "contract a plugin author implements. `PluginCapabilities` in",
        "`core/plugin_capabilities.py` is core's **internal** view *over* a loaded",
        "plugin — it points the opposite way and is not an authoring surface.",
        "",
        "A capability marked `optional` degrades when the plugin does not implement",
        "its hook: the named `compatibility.py` fallback runs instead, returning",
        "cardiac data only for `org.cardiacfoam` and a neutral value for every other",
        "plugin. The two sweep fallbacks cannot be neutral and refuse by hook name.",
        "",
        "| capability | protocol | adapts | consumed by | fallback | status |",
        "|---|---|---|---|---|---|",
    ]
    for seam in seams:
        lines.append(
            f"| `{seam.field}` | `{seam.protocol}` | {_code_list(seam.adapts)} "
            f"| {_code_list(seam.consumed_by)} | {_code_list(seam.fallback)} "
            f"| {_cell(seam.status)} |"
        )
    lines += ["", f"{len(seams)} capability seams.", "", END_MARKER]
    return "\n".join(lines)


def splice(document: str, table: str) -> str:
    if BEGIN_MARKER in document and END_MARKER in document:
        head = document.split(BEGIN_MARKER)[0]
        tail = document.split(END_MARKER, 1)[1]
        return f"{head}{table}{tail}"
    separator = "" if document.endswith("\n\n") else "\n"
    return f"{document}{separator}\n## Plugin capability seams\n\n{table}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if ARCHITECTURE.md is not up to date, writing nothing",
    )
    args = parser.parse_args()

    table = render(collect_seams())
    document = ARCHITECTURE.read_text()
    updated = splice(document, table)

    if args.check:
        if document != updated:
            print(
                "ARCHITECTURE.md capability seam table is stale. "
                "Regenerate with: python3 scripts/export-capability-seams.py",
                file=sys.stderr,
            )
            return 1
        print("ARCHITECTURE.md capability seam table is up to date.")
        return 0

    ARCHITECTURE.write_text(updated)
    print(f"Wrote {len(collect_seams())} capability seams to {ARCHITECTURE.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
