/*---------------------------------------------------------------------------*\
License
    This file is part of cardiacFoam.
\*---------------------------------------------------------------------------*/

#ifndef TNNPModelInfo_H
#define TNNPModelInfo_H

#include "../ionicModel/ionicModelFamilyInfo.H"

namespace Foam
{

const ionicModelFamilyInfo& TNNPFamilyInfo();

}

#endif

// ************************************************************************* //
