#!/usr/bin/env bash
cd "${0%/*}" || exit    # Run from this directory
set -e

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase0

rm -fv ./*.gnuplot ./*.dat gmsh/*.msh ./*.obj ./geometry.stl ./*.fms
