#!/bin/bash
cd "${0%/*}" || exit 1
set -e

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Options:
#   --plot   run ./plotVoltage on the traces after the solve.
plot=false
for arg in "$@"; do
    case "$arg" in
        --plot) plot=true ;;
        *) echo "Unknown argument '$arg'. Use --plot." ; exit 1 ;;
    esac
done

runApplication blockMesh
runApplication cardiacFoam

if $plot; then
    ./plotVoltage
fi
