#!/bin/bash

for i in {1..5}
do
    echo "Mesh $i"

    # Copy base case
    CASE="mesh$i"
    cp -r base "${CASE}"

    # Change blockMeshDict
    cd "${CASE}"
    echo "    Replacing the blockMeshDict"
    cp system/blockMeshDict.$i system/blockMeshDict

    # Run the case in the background
    if [[ $i -gt 2 ]]
    then
        # Run in the foreground
        echo "    Running ${CASE} in parallel"
        ./Allrun parallel &> log."${CASE}"
    else
        # Run in the background
        echo "    Running ${CASE} in serial"
        ./Allrun &> log."${CASE}" &
    fi

    # Return to the parent directory
    cd ..
    echo
done

echo "Waiting for jobs to complete"
wait
echo "All jobs done"
