#!/bin/bash
cd "${0%/*}" || exit 1
set -e

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

parallelRun=false
for arg in "$@"; do
    case "$arg" in
        parallel)
            parallelRun=true
            ;;
    esac
done

runApplication blockMesh

if $parallelRun; then
    runApplication decomposePar
    runParallel cardiacFoam
    runApplication reconstructPar
    runApplication redistributeRestartState
else
    runApplication cardiacFoam
fi

runApplication -o postProcess -func rotorpoints -latestTime
