#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [[ $1 == "parallel" ]]
then
    # Decompose the mesh
    runApplication decomposePar

    # Run the solver in parallel
    runParallel cardiacFoam

    # Reconstruct the results
    runApplication reconstructPar
else
    # Run the solver in serial
    runApplication cardiacFoam
fi
