/*---------------------------------------------------------------------------*\
License
    This file is part of cardiacFoam.
\*---------------------------------------------------------------------------*/

#ifndef ORdModelInfo_H
#define ORdModelInfo_H

#include "../ionicModel/ionicModelFamilyInfo.H"

namespace Foam
{

const ionicModelFamilyInfo& ORdFamilyInfo();

}

#endif

// ************************************************************************* //
