/*---------------------------------------------------------------------------*\
License
    This file is part of cardiacFoam.
\*---------------------------------------------------------------------------*/

#ifndef BuenoOrovioModelInfo_H
#define BuenoOrovioModelInfo_H

#include "../ionicModel/ionicModelFamilyInfo.H"

namespace Foam
{

const ionicModelFamilyInfo& BuenoOrovioFamilyInfo();

}

#endif

// ************************************************************************* //
