#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh -dict system/blockMeshDict.2D

if [[ $1 == "parallel" ]]
then
    # Decompose the mesh
    runApplication decomposePar

    # Run the solver in parallel
    runParallel manufactFoam

    # Reconstruct the results
    runApplication reconstructPar
else
    # Run the solver in serial
    runApplication manufactFoam
fi

