from __future__ import annotations

from .manufactured_fda import (
    BLOCK_MESH_DICT_TEMPLATE,
    BLOCK_MESH_RESOLUTION_BY_DIMENSION,
    DT_VALUES,
    DIMENSIONS,
    NUMBER_CELLS,
    OUTPUT_DIR_NAME,
    PIECEWISE_SWEEP,
    RUN_CASE_SCRIPT_RELPATH,
)


TUTORIAL_NAME = "manufacturedFDABidomain"
CASE_DIR_NAME = "manufacturedSolutions/bidomain"
SETUP_DIR_NAME = "setupManufacturedFDA"
SOLVER_TYPES = ("implicit",)
ELECTRO_PROPERTIES_SCOPE = "bidomainSolverCoeffs"
RUN_SCRIPT_RELPATH = RUN_CASE_SCRIPT_RELPATH
RUN_IN_PARALLEL = True
VERIFICATION_MODEL_TYPE = "manufacturedFDABidomainVerifier"
ECG_ENABLED = False
ECG_REFERENCE_QUADRATURE_ORDER = 96
ECG_CHECK_QUADRATURE_ORDERS = (6, 12, 24, 48)
ECG_ELECTRODES_BY_DIMENSION = {}

__all__ = [
    "BLOCK_MESH_DICT_TEMPLATE",
    "BLOCK_MESH_RESOLUTION_BY_DIMENSION",
    "CASE_DIR_NAME",
    "DT_VALUES",
    "DIMENSIONS",
    "ECG_CHECK_QUADRATURE_ORDERS",
    "ECG_ELECTRODES_BY_DIMENSION",
    "ECG_ENABLED",
    "ECG_REFERENCE_QUADRATURE_ORDER",
    "ELECTRO_PROPERTIES_SCOPE",
    "NUMBER_CELLS",
    "OUTPUT_DIR_NAME",
    "PIECEWISE_SWEEP",
    "RUN_IN_PARALLEL",
    "RUN_SCRIPT_RELPATH",
    "SETUP_DIR_NAME",
    "SOLVER_TYPES",
    "TUTORIAL_NAME",
    "VERIFICATION_MODEL_TYPE",
]
