#!/bin/bash

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

parallelRun=false
for arg in "$@"; do
    case "$arg" in
        parallel)
            parallelRun=true
            ;;
    esac
done

runApplication blockMesh

if $parallelRun; then
    runApplication decomposePar
    runParallel cardiacFoam
    runApplication reconstructPar
else
    runApplication cardiacFoam
fi

# Run post-processing function object for the smoke-test window
runApplication -o postProcess -func smokeCheck
runApplication -o postProcess -func Niedererpoints -latestTime
runApplication -o postProcess -func Niedererlines -latestTime
