#!/bin/bash
#-------------------------------------------------------------------------------
# Allclean script for boundary-constrained electromechanics verification case
#-------------------------------------------------------------------------------

cd "${0%/*}" || exit 1

shopt -s extglob
rm -rf !("0"|*[^0-9]*)
rm -rf 0.*

rm -rf constant/polyMesh
rm -rf constant/electro/polyMesh
rm -rf constant/solid/polyMesh
rm -rf platforms
rm -rf processor*
rm -f log.*
rm -f constant/electro/electroProperties.withDefaultValues
rm -f constant/electroMechanicalProperties.withDefaultValues
rm -f constant/solid/mechanicalProperties.withDefaultValues
rm -f constant/solid/solidProperties.withDefaultValues
