#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf case.foam monitorFile postProcessing
rm -f log.*

# The mesh and anatomy fields are copied in from ../mesh/ by Allrun, not
# supplied source in this case directory - remove the copies. t is
# derived by setExprFields from tm, also not source.
rm -rf constant/polyMesh
rm -f 0/fiber 0/sheet 0/sheetNormal 0/tm 0/tv 0/apicobasal 0/Conductivity 0/t
