#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# No blockMesh call here: the tetrahedral mesh is built and imported via
# gmsh + gmshToFoam by setup/run_tet_sweep.sh before this script runs
# (mirrors monodomainTetMMS/Allrun).

if [[ $1 == "parallel" ]]
then
    # Decompose the mesh
    runApplication decomposePar

    # Run the solver in parallel
    runParallel cardiacFoam

    # Reconstruct the results
    runApplication reconstructPar
else
    # Run the solver in serial
    runApplication cardiacFoam
fi
