#!/bin/bash

# Source required functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
source solids4FoamScripts.sh

# Define configurations as space-separated strings
configs=(
    "BASE=base/snes NAME=hex.hypre PETSC_FILE=petscOptions.hypre"
    "BASE=base/segregated NAME=hex.seg"
)
# SNES segregated approach
#    "BASE=base/snes NAME=hex.seg.hypre PETSC_FILE=petscOptions.seg.hypre"

# Define start and end mesh indices
# Mesh input files are defined from 1 to 4
START_MESH=1
END_MESH=4


# Detect the CPU type: we append this to the case name
if [[ "$OSTYPE" == "darwin"* ]]
then
    # macOS
    CPU_TYPE=$(sysctl -n machdep.cpu.brand_string | sed 's/[^a-zA-Z0-9]/_/g')
elif [[ -f /proc/cpuinfo ]]
then
    # Linux
    CPU_TYPE=$(grep -m 1 "model name" /proc/cpuinfo | awk -F': ' '{print $2}' | sed 's/[^a-zA-Z0-9]/_/g')
else
    # Fallback if neither method works
    CPU_TYPE="Unknown_CPU"
fi


# Create timestamped working directory for this run
DATE=$(date +%Y%m%d_%H%M%S)
RUN_DIR="run_${CPU_TYPE}_${DATE}"
echo "Creating ${RUN_DIR}"
mkdir "${RUN_DIR}"

# Enter the run directory
cd "${RUN_DIR}"

# Iterate through configurations
for config in "${configs[@]}"
do
    # Parse the configuration string
    eval $config
    echo; echo "***************************************"
    echo "Running configuration: $config"
    echo "***************************************"

    # Define results summary file name
    SUMMARY="${NAME}.summary.txt"
    echo "# Mesh Time Mem D_L2 D_Linf S_L2 S_Linf" > "${SUMMARY}"

    # Loop over mesh densities in each configuration
    for i in `seq $START_MESH $END_MESH`
    do
        CASE="${NAME}.$i"
        echo; echo "Processing case: $CASE"

        # Prepare the case
        cp -r "../${BASE}" "${CASE}"
        cd "$CASE"

        # Replace the blockMeshDict file
        if [[ ! -f "system/blockMeshDict.$i" ]]
        then
            echo "Cannot find ${CASE}/system/blockMeshDict.$i: please add it to ${BASE}/system/"; echo
            exit 1;
        else
            echo "Copying ${CASE}/system/blockMeshDict.$i to ${CASE}/system/blockMeshDict"
            \cp "system/blockMeshDict.$i" system/blockMeshDict
        fi

        # Replace the extrudeMeshDict file
        if [[ ! -f "system/extrudeMeshDict.$i" ]]
        then
            echo "Cannot find ${CASE}/system/extrudeMeshDict.$i: please add it to ${BASE}/system/"; echo
            exit 1;
        else
            echo "Copying ${CASE}/system/extrudeMeshDict.$i to ${CASE}/system/extrudeMeshDict"
            \cp "system/extrudeMeshDict.$i" system/extrudeMeshDict
        fi

        # Create the mesh
        solids4Foam::runApplication blockMesh
        solids4Foam::runApplication extrudeMesh
        solids4Foam::runApplication createPatch -overwrite

        # Update the PETSc options file
        if [ -n "${PETSC_FILE}" ]; then
            sed -i "/^\s*optionsFile /s|^.*|    optionsFile ${PETSC_FILE};|" constant/solidProperties
        fi

        # Run the solver
        # If "gtime" is available (could be called "time" on Linux), use it to
        # record the max memory usage
        if command -v gtime &> /dev/null
        then
            echo "Running solids4Foam on ${CASE} with gtime"
            gtime -f "Maximum resident set size (kbytes): %M" mpirun -np 1 solids4Foam &> log.solids4Foam
        elif command -v time &> /dev/null
        then
            echo "Running solids4Foam on ${CASE} with time"
            gtime -f "Maximum resident set size (kbytes): %M" mpirun -np 1 solids4Foam &> log.solids4Foam
        else
            echo "Running solids4Foam on ${CASE}"
            # Strange PETSc issue on Macbook where I need to use mpirun for serial
            #solids4Foam::runApplication solids4Foam
            mpirun -np 1 solids4Foam &> log.solids4Foam
        fi

        # Run extractIdealisedVentricleResults
        solids4Foam::runApplication extractIdealisedVentricleResults

        # Extract results from solver log and append them to a summary file
        echo; echo "Appending results to ${SUMMARY}"
        if grep -q "Maximum resident" log.solids4Foam; then
            MAX_MEMORY=$(grep "Maximum resident" log.solids4Foam | awk '{print int($6 / 1000)}')
        else
            MAX_MEMORY="NaN"
        fi

        # Record the time
        CLOCK_TIME=$(grep "ClockTime" log.solids4Foam | tail -n 1 | awk '{print $7}')

        # Write data to file
        echo "$i $CLOCK_TIME $MAX_MEMORY" >> ../"${SUMMARY}"

        cd ..
    done

    # Print summary file
    echo; echo "${SUMMARY} file:"; cat "${SUMMARY}"; echo
done

# Create plots if gnuplot in installed
if command -v gnuplot &>/dev/null
then
    # Copy gnuplot scripts
    cp ../plotScripts/*gnuplot .
    cp ../plotScripts/orderOfAccuracySlopes*.dat .

    # Run all scripts
    for f in *gnuplot
    do
        echo "Running gnuplot on $f"
        gnuplot "$f"
    done
fi

# Extract comparison of JFNK and segregated for the hex meshes
if [[ -f hex.hypre.summary.txt && -f hex.seg.summary.txt ]]
then
    # Define input files
    FILE1="hex.hypre.summary.txt"
    FILE2="hex.seg.summary.txt"
    OUTPUT="tableJFNKvsSeg_ventricle.tex"

    # Define mesh sizes for the rows in the table
    MESH_SIZES=("\$1\,620\$" "\$12\,960\$" "\$103\,680\$" "\$829\,440\$")

    # Extract columns and write to the output file
    {
        for i in $(seq 1 $((${#MESH_SIZES[@]}))); do
            # Extract columns 2 and 3 from each file
            F1C2=$(awk "NR==$((i + 1)) {print \$2}" "$FILE1")
            F1C3=$(awk "NR==$((i + 1)) {print \$3}" "$FILE1")
            F2C2=$(awk "NR==$((i + 1)) {print \$2}" "$FILE2")
            F2C3=$(awk "NR==$((i + 1)) {print \$3}" "$FILE2")

            if [[ i -eq 1 ]]
            then
                echo -e "\t\\\textbf{Ventricle}\t& ${MESH_SIZES[i-1]}\t& $F1C2 & $F1C3 & $F2C2 & $F2C3 \\\\\\"
            elif [[ i -eq 2 ]]
            then
                echo -e "\t\\emph{3-D, static}\t& ${MESH_SIZES[i-1]}\t& $F1C2 & $F1C3 & $F2C2 & $F2C3 \\\\\\"
            elif [[ i -eq 3 ]]
            then
                echo -e "\t\\emph{hyperelastic}\t& ${MESH_SIZES[i-1]}\t& $F1C2 & $F1C3 & $F2C2 & $F2C3 \\\\\\"
            else
                echo -e "\t\t\t\t& ${MESH_SIZES[i-1]}\t& $F1C2 & $F1C3 & $F2C2 & $F2C3 \\\\\\"
            fi
        done
    } > "$OUTPUT"

    echo -e "\hline" >> "$OUTPUT"

    echo; echo "Table generated in $OUTPUT"
fi

# Exit the run directory
cd ..

echo; echo; echo "Done!"; echo
echo "View the PDF files in ${RUN_DIR}"
echo; echo $(date)
echo; echo
