#!/bin/bash
#-------------------------------------------------------------------------------
# Allclean script for electro-mechanical coupling tutorial
#-------------------------------------------------------------------------------

cd "${0%/*}" || exit 1

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh
rm -rf constant/electro/polyMesh
rm -rf constant/solid/polyMesh
rm -rf processor*
rm -f constant/electro/electroProperties.withDefaultValues
