#!/usr/bin/env python3

import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
SRC_DIR = SCRIPT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from pipeline import (
    detect_start_stage,
    run_pipeline,
)
from sort_folder import sort_folder


UTILITY_NAME = "cellML2foam"


def foam_banner(args, start, stages):
    print(f"--> {UTILITY_NAME} v2 (Python-driven)")
    print(f"    Input        : {args.input}")
    print(f"    Start stage  : {start}")
    print(f"    End stage    : {args.to}")
    print(f"    Model name   : {args.model}")
    print(f"    Output dir   : {args.outdir}")
    print(f"    Pipeline     : {' -> '.join(stages)}")
    print("")


def print_manual_steps_notice():
    print(
        """
============================================================
MANUAL STEPS REQUIRED
============================================================

The generated OpenFOAM ionic model may still require manual
edits before it is ready for use, depending on the success
of the automated discovery.

1) Verify ALGEBRAIC[Iion_cm]
--------------------------------
The tool has attempted to map the total ionic current automatically.
PLEASE VERIFY in the <ModelName_Year>.C file that ALGEBRAIC[Iion_cm]
correctly represents the sum of transmembrane currents.

    ALGEBRAIC[Iion_cm] = ALGEBRAIC[<sum_of_currents>];

This definition is model-specific and must be verified
against the original publication.


2) Remove redundant voltage and stimulus terms
-----------------------------------------------
Please inspect the functions and:

- Remove the existing RATES[V], as referred, generated by Myokit
  (Vm is handled at the end of the function for OpenFOAM)

- Remove unused stimulus-related symbols from <ModelName_Year>.H and Names.H
  (Examples: AV_pace, t, pace, t_amplitude, t_end)


3) Flags for tissue definition
-----------------------------------------------
- If there is data dependent on tissue type, map the used variable to tissueFlag:

    tissueFlag == 1 : endo
    tissueFlag == 2 : mid
    tissueFlag == 3 : epi


4) Hash table for voltage dependence
-----------------------------------------------
If the model has voltage dependence on parameters (e.g., gating variables), 
implement the hash table lookup for Vm in <ModelName_Year>DependencyMap().

Check the existing examples in the cardiacFoam library in src/ionicModels.

============================================================
"""
    )


def parse_args():
    p = argparse.ArgumentParser(
        prog=UTILITY_NAME,
        description="Convert CellML models to OpenFOAM-ready ionic model code (Modernized v2)",
    )

    p.add_argument(
        "input",
        type=Path,
        help="Input file (.cellml, .mmt, .c)",
    )

    p.add_argument(
        "--from",
        dest="start",
        help="Pipeline stage to start from (auto-detected if omitted)",
    )

    p.add_argument(
        "--to",
        dest="to",
        default="openfoam",
        help="Pipeline stage to end at (default: openfoam)",
    )

    p.add_argument(
        "--model",
        help="Model name (used for output files)",
    )

    p.add_argument(
        "--outdir",
        type=Path,
        default=Path("."),
        help="Output directory (default: current directory)",
    )

    p.add_argument(
        "--verbose",
        action="store_true",
        help="Verbose output",
    )

    return p.parse_args()


def main():
    args = parse_args()

    if not args.input.exists():
        print(f"Error: input file not found: {args.input}")
        sys.exit(1)

    try:
        start = args.start or detect_start_stage(args.input)

        # Execute pipeline
        result = run_pipeline(
            args.input,
            start=start,
            end=args.to,
            model=args.model,
            verbose=args.verbose,
        )

        if result is not None:
            # Reconstruct stages for the banner if it returned a dict
            stages_list = ["openfoam"] # Minimalist hint
            foam_banner(args, start, stages_list)
            
            # Only create ionic folder if we reached openfoam
            if args.to == "openfoam":
                if args.model is None:
                    raise ValueError("--model <ModelName_Year> is required")

                if "_" not in args.model:
                    raise ValueError("--model must be ModelName_Year")

                model, year = args.model.rsplit("_", 1)
                year = int(year)

                sort_result = sort_folder(
                    model=model,
                    year=year,
                    outdir=args.outdir,
                    verbose=args.verbose,
                )
                if args.verbose:
                    print(f"    Created: {len(sort_result['created'])} files")
                    print(f"    Moved:   {len(sort_result['moved'])} files")
                print_manual_steps_notice()

    except Exception as e:
        print(f"Error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
