#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Default to 1D unless an argument selects another dimension
DIM=${1:-1D}
cp system/blockMeshDict.${DIM} system/blockMeshDict

runApplication blockMesh
runApplication topoSet
runApplication setTorsoOrganConductivityField

runApplication cardiacFoam
