#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

wclean couplingModels
wclean genericWriter
wclean ionicModels
wclean verificationModels
wclean activeTensionModels
wclean electroModels
wclean electroMechanicalModels

