#!/bin/bash
cd "${0%/*}" || exit 1    # run from this directory

# Stop at first error
set -e

wclean couplingModels
wclean genericWriter
wclean ionicModels
wclean verificationModels
wclean activeTensionModels
wclean electroModels
wclean electroMechanicalModels
