#!/bin/bash
cd "${0%/*}" || exit 1
set -e

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

PARALLEL=false

if [[ "${1:-}" == "parallel" ]]
then
    PARALLEL=true
fi

runApplication blockMesh
runApplication topoSet
runApplication setTorsoOrganConductivityField

if ${PARALLEL}
then
    runApplication decomposePar
    runParallel cardiacFoam
    runApplication reconstructPar
else
    runApplication cardiacFoam
fi
